### ISSUE TITLE
Host on Netlify

### ISSUE THREAD

**Issue by codekeyz** [NNEAfric/hover-site#1]
Consider going to Netlify and Add this repo. It will automatically install the necessary dependencies and take the source code up as a live site.

**Comment by NNEAfric** [comment]
Ok cool.
Imma do that right away.

**Comment by codekeyz** [comment]
Ohk. Do so and close the issue.

**Comment by NNEAfric** [comment]
I just deployed it to firebase.
Check it out via the link below.
https://todo-d518d.firebaseapp.com/
